<?php
/**
Plugin Name: Suppress WHIP Notification
Description: Suppresses WHIP notifications generated by Yoast SEO and similar plugins.
Version: 1.0
Author: David E. Smith
Author URI: https://xlii.io/
License: WTFPL
*/

add_action( 'admin_enqueue_scripts', 'ws_yoast_buster' );

function ws_yoast_buster() {
	wp_enqueue_script( 'ws-yoast-buster',
		plugins_url( 'yoast.js', __FILE__ ) );
}
